In [1]:
#import numpy as np
import pandas as pd
import statistics as st

In [24]:
dataset=pd.read_csv('winequality-red.csv',sep=";",nrows=1000)
dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34,0.9978,3.51,0.56,9.4,5

In [26]:
dataset.query('pH>=3.26')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.90,0.076,11.0,34,0.99780,3.51,0.56,9.4,5
2,7.8,0.76,0.04,2.30,0.092,15.0,54,0.99700,3.26,0.65,9.8,5
4,7.4,0.70,0.00,1.90,0.076,11.0,34,0.99780,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.80,0.075,13.0,40,0.99780,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.60,0.069,15.0,59,0.99640,3.30,0.46,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
993,7.1,0.34,0.28,2.00,0.082,31.0,68,0.99694,3.45,0.48,9.4,5
995,7.7,0.60,0.06,2.00,0.079,19.0,41,0.99697,3.39,0.62,10.1,6
996,5.6,0.66,0.00,2.20,0.087,3.0,11,0.99378,3.71,0.63,12.8,7
997,5.6,0.66,0.00,2.20,0.087,3.0,11,0.99378,3.71,0.63,12.8,7
999,6.4,0.69,0.00,1.65,0.055,7.0,12,0.99162,3.47,0.53,12.9,6

In [27]:
mean_var=dataset['pH'].mean()

In [28]:
mean_var

3.2990999999999997

In [23]:
#dataset.chlorides.median()
dataset['chlorides'].median()

0.081

In [20]:
dataset.density.mode()

0    0.9972
dtype: float64

In [21]:
dataset.density.value_counts()

0.99720    35
0.99760    34
0.99680    33
0.99800    29
0.99640    25
           ..
0.99761     1
0.99517     1
0.99530     1
0.99733     1
0.99901     1
Name: density, Length: 240, dtype: int64

In [16]:
range=dataset['fixed acidity'].max()-dataset['fixed acidity'].min()
range

11.3

In [18]:
dataset['variance']=dataset['fixed acidity']-dataset['fixed acidity'].mean()
dataset

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,variance
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,-0.919637
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,-0.519637
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,-0.519637
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,2.880363
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,-0.919637
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,-2.119637
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,-2.419637
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,-2.019637
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,-2.419637
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6,-2.319637

In [19]:
dataset['volatile acidity'].var()

0.03206237765155147

In [20]:
dataset['volatile acidity'].std()

0.17905970415353498

In [23]:
dataset.quantile([.25, .75])

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,variance
0.25,7.1,0.39,0.09,1.9,0.07,7.0,22.0,0.995600,3.21,0.55,9.5,5.0,-1.219637
0.75,9.2,0.64,0.42,2.6,0.09,21.0,62.0,0.997835,3.40,0.73,11.1,6.0,0.880363

In [24]:
dataset.skew()

fixed acidity           0.982751
volatile acidity        0.671593
citric acid             0.318337
residual sugar          4.540655
chlorides               5.680347
free sulfur dioxide     1.250567
total sulfur dioxide    1.515531
density                 0.071288
pH                      0.193683
sulphates               2.428672
alcohol                 0.860829
quality                 0.217802
variance                0.982751
dtype: float64

In [ ]:
#home work Outilers

In [30]:
dataset.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')